#!/bin/bash
# setup for RVM

# RVM support
# if [ -f ~/.rvm/bin/rvm ]; then
#     . ~/.rvm/bin/rvm
# fi
if [ -f ~/.rvm/scripts/rvm ]; then
    . ~/.rvm/scripts/rvm
fi
if [ -f ~/.rvm/current ]; then
    . ~/.rvm/current
fi
export PATH=$HOME/.rvm/bin:$PATH

# gemdir() {
#     if [[ -z "$1" ]] ; then
#         echo "gemdir expects a parameter, which should be a valid rvm Ruby selector"
#     else
#         rvm "$1"
#         cd `rvm gemdir`
#         pwd
#     fi
# }
