#!/bin/bash
# environment variables used by Amazon EC2 command-line tools

export EC2_HOME=$HOME/ec2
export EC2_PRIVATE_HOME=$HOME/.ec2
export EC2_URL=https://ec2.us-east-1.amazonaws.com/

export EC2_PRIVATE_KEY=$HOME/.ec2/pk-TAQWOMJPNANVPY4O24PYZX2RYWPJYA2O.pem
export EC2_CERT=$HOME/.ec2/cert-TAQWOMJPNANVPY4O24PYZX2RYWPJYA2O.pem
export EC2_KEYPAIR=$HOME/.ec2/id_rsa-craigc-keypair
export EC2_KEYPAIR_NAME=craigc-keypair
