#!/bin/bash
# setup for Ruby

export RUBYLIB=$HOME/lib/ruby

# RVM support
if [ -f ~/.rvm/bin/rvm ]; then
    . ~/.rvm/bin/rvm
fi
if [ -f ~/.rvm/current ]; then
    . ~/.rvm/current
fi
export PATH=$HOME/.rvm/bin:$PATH
